tp_connection_get_detailed_error: fix a memory leak
If we were invalidated without a detailed error, we'd assign a new empty
hash table to a const out parameter, leaking it.

Instead, keep creating the empty hash table lazily, but stash it in priv
so it will be freed in our destructor.